project structure
crimson-dev/crimson pull request #3
Opened 2021-06-04 13:10 UTC by toxdes

For #1 Created a basic `Hello world` project, with typescript template. Suggestions are welcome.

2021-06-04 15:18 UTC, ankitbko requested changes

2021-06-04 15:18 UTC, ankitbko commented on src/mobile/package.json
> +    "typescript": "^3.8.3"
Can we use latest version?

2021-06-04 15:18 UTC, ankitbko commented on src/mobile/app.json
> +  "name": "mobile",
Do we want to change the name?

2021-06-04 15:18 UTC, ankitbko commented on src/mobile/tsconfig.json
> +    // "sourceMap": true,                     /* Generates corresponding '.map' file. */
enable this

2021-06-04 15:18 UTC, ankitbko commented on src/mobile/tsconfig.json
> +    // "noImplicitAny": true,                 /* Raise error on expressions and declarations with an implied 'any' type. */
and this

2021-06-04 15:18 UTC, ankitbko commented on src/mobile/tsconfig.json
> +    /* Additional Checks */
and all these

2021-06-04 15:18 UTC, ankitbko commented on src/mobile/tsconfig.json
> +    /* Experimental Options */
and these

2021-06-04 15:18 UTC, ankitbko commented on src/mobile/.prettierrc.js
> +};
add following
```
"printWidth": 128,

```

2021-06-04 17:48 UTC, Cinnybun commented on src/mobile/tsconfig.json
> +    /* Experimental Options */
Should I click Resolve converstation?

2021-06-04 18:39 UTC, ankitbko commented
Please add a `setup.md` and document list of softwares (android sdk, android platform version, node ver etc) which are necessary to build this app. And probably also include instructions on how to build/test/run the app.

2021-06-04 18:55 UTC, Cinnybun approved these changes, later dismissed
LGTM

2021-06-05 09:03 UTC, ankitbko commented on src/mobile/setup.md
> +# Development
Also add the prerequisites - 
1. Android SDK
2. JAVA

Also add how to generate avd for android emulator after installing SDK -

```
sdkmanager --install 'system-images;android-29;google_apis_playstore;x86_64'
sdkmanager --install 'extras;intel;Hardware_Accelerated_Execution_Manager'

.\avdmanager.bat create avd -f -n crimsonAVD -d 17 -b google_apis/x86_64 --package 'system-images;android-29;google_apis;x86_64'
```

2021-06-05 09:06 UTC, ankitbko commented on src/mobile/setup.md
> +# Development
And how to run the emulator - 

```
emulator -avd crimsonAVD
```

2021-06-06 05:08 UTC, ankitbko submitted a review, later dismissed

2021-06-06 07:01 UTC, tarunsingh495 commented
Tested locally. Works fine for me.

2021-06-06 07:06 UTC, ME-ON1 approved these changes
looks fine to me

2021-06-06 07:13 UTC, tarunsingh495 approved these changes
tested Locally . Works fine for me.

2021-06-06 07:14 UTC, darkfusion90 approved these changes

2021-06-06 07:15 UTC, merged